// src/modules/people-finder.ts
// Option B: AI-suggested contacts — no scraping, no LinkedIn risk

import { Contact } from '../types';
import { log } from '../utils/helpers';

export async function findContacts(company: string): Promise<Contact[]> {
  // Contacts are now generated by Gemini in ai-processor.ts
  // This module is kept for future use
  log('people', `Contacts for ${company} handled by AI processor`);
  return [];
}